### PR TITLE
add usync and usync files for schema and content

### LINKED ISSUE #26: Remove test site db and use uSync instead
### Feature summary

See the thoughts I've been having on the Opinionated Package Starter Template repo re the test site having a committed db...

https://github.com/LottePitcher/opinionated-package-starter/issues/2

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by jemayn**
Fixes #26 

Hey @LottePitcher 

This PR sets up unattended install using the same admin user credentials as mentioned in the contributing doc.

It also contains usync schema and content files for the stuff that was in the comitted SQL Lite db, which has been removed in this PR.

Without usync complete we cannot generate an Editor user through usync - so would have to either run some code that adds it via the Umbraco API's fx on startup. Otherwise we could just not automatically add it, and instead update the contributing docs with a note on how to test by creating the user locally?

Let me know what you think, and if there is anything else I should do for this PR 🙂

### CODE REVIEW

**Comment by LottePitcher** [comment]
Well this looks great, thank you @jemayn !

But yes, of course, the Editor user...

I like the idea of being able to "just" spin up the test site and everything being there ready for testing without having to follow lots of steps. And I don't think it matters what goes into the test site really, the priority of that site is to remove as many barriers as possible for collaborators and having a good testing experience. Best practises / "normal" approaches aren't really relevant.

So I think adding the user via code is a good idea, if you agree? Would you be up for giving that a go, either in this, or as a separate PR?

**Comment by jemayn** [comment]
@LottePitcher 

I think adding via code is a good solution, especially as we will most likely require that user in stuff like the playwright tests coming in #30 🙂

Will take a look and get it added into this PR when I get the time.

**Comment by jemayn** [comment]
Hey @LottePitcher 

I wrote a quick startup notification handler that checks if the editor exists, and if not it creates it.
Also switched uSync settings so it automatically imports content and schema if the db is empty 😊

**Comment by LottePitcher** [comment]
Works wonderfully @jemayn - SuperTak 😊

**Comment by LottePitcher** [comment]
Thank you @jemayn - the changes you did here meant it was super easy for me to add a v12 and a v13 test site to the repo. The package didn't work on v13 so multi-targeting needed to be added so it could be fixed. Fixed, tested, and a new release done!

Happy holidays :)

**Pull request merged**
